export const dummyData = [
        {
          "SIGUN_NM": "가평군",
          "BIZPLC_NM": "청평우리병원",
          "REFINE_ZIPNO": "477810",
          "REFINE_ROADNM_ADDR": "경기도 가평군 청평면 경춘로 791-11",
          "REFINE_LOTNO_ADDR": "경기도 가평군 청평면 441번지 43호",
          "LICENSG_DE": "20050215",
          "BSN_STATE_NM": "운영중",
          "CLSBIZ_DE": "",
          "MEDINST_SPCS_NM": "",
          "SICKBD_CNT": "198",
          "MEDSTAF_CNT": "20",
          "HOSPTLRM_CNT": "34",
          "TREAT_SBJECT_CONT": "마취통증의학과, 피부과, 소아청소년과, 내과, 신경과, 영상의학과, 가정의학과, 정신건강의학과",
          "TOT_AR": "2738",
          "REFINE_WGS84_LAT": "37.7371643740",
          "REFINE_WGS84_LOGT": "127.4153657538"
        },
        {
          "SIGUN_NM": "가평군",
          "BIZPLC_NM": "HJ매그놀리아국제병원",
          "REFINE_ZIPNO": "477855",
          "REFINE_ROADNM_ADDR": "경기도 가평군 설악면 미사리로 267-177",
          "REFINE_LOTNO_ADDR": "경기도 가평군 설악면 송산리 460번지",
          "LICENSG_DE": "20030517",
          "BSN_STATE_NM": "운영중",
          "CLSBIZ_DE": "",
          "MEDINST_SPCS_NM": "",
          "SICKBD_CNT": "117",
          "MEDSTAF_CNT": "84",
          "HOSPTLRM_CNT": "48",
          "TREAT_SBJECT_CONT": "정형외과, 성형외과, 이비인후과, 가정의학과, 재활의학과, 신경과, 외과, 내과, 마취통증의학과, 영상의학과, 정신건강의학과, 산부인과",
          "TOT_AR": "22922",
          "REFINE_WGS84_LAT": "37.6908873205",
          "REFINE_WGS84_LOGT": "127.5213882297"
        },
        {
          "SIGUN_NM": "가평군",
          "BIZPLC_NM": "노체리안드리자애병원",
          "REFINE_ZIPNO": "12432",
          "REFINE_ROADNM_ADDR": "경기도 가평군 조종면 꽃동네길 46 (노체리안드리자애병원)",
          "REFINE_LOTNO_ADDR": "경기도 가평군 조종면 하판리 540번지 2호",
          "LICENSG_DE": "19951218",
          "BSN_STATE_NM": "운영중",
          "CLSBIZ_DE": "",
          "MEDINST_SPCS_NM": "",
          "SICKBD_CNT": "99",
          "MEDSTAF_CNT": "15",
          "HOSPTLRM_CNT": "16",
          "TREAT_SBJECT_CONT": "외과, 영상의학과, 정신건강의학과, 내과",
          "TOT_AR": "6511.34",
          "REFINE_WGS84_LAT": "37.8848309123",
          "REFINE_WGS84_LOGT": "127.3503711670"
        },
        {
          "SIGUN_NM": "가평군",
          "BIZPLC_NM": "국군청평병원",
          "REFINE_ZIPNO": "477809",
          "REFINE_ROADNM_ADDR": "경기도 가평군 청평면 경춘로 926",
          "REFINE_LOTNO_ADDR": "경기도 가평군 청평면 청평리 567번지 21호 사서함",
          "LICENSG_DE": "19940523",
          "BSN_STATE_NM": "폐업 등",
          "CLSBIZ_DE": "20170919",
          "MEDINST_SPCS_NM": "",
          "SICKBD_CNT": "350",
          "MEDSTAF_CNT": "65",
          "HOSPTLRM_CNT": "6",
          "TREAT_SBJECT_CONT": "내과, 신경과, 정신건강의학과, 외과, 정형외과, 신경외과, 흉부외과, 안과, 이비인후과, 피부과, 비뇨기과, 영상의학과, 진단검사의학과, 재활의학과, 가정의학과, 응급의학과, 치과",
          "TOT_AR": "999999",
          "REFINE_WGS84_LAT": "37.7436907006",
          "REFINE_WGS84_LOGT": "127.4295840866"
        },
        {
          "SIGUN_NM": "고양시",
          "BIZPLC_NM": "든든한병원",
          "REFINE_ZIPNO": "411809",
          "REFINE_ROADNM_ADDR": "경기도 고양시 일산서구 하이파크2로 60 (덕이동, 든든한빌딩 3~11층)",
          "REFINE_LOTNO_ADDR": "경기도 고양시 일산서구 덕이동 1551번지 든든한빌딩3~11층",
          "LICENSG_DE": "20150714",
          "BSN_STATE_NM": "운영중",
          "CLSBIZ_DE": "",
          "MEDINST_SPCS_NM": "",
          "SICKBD_CNT": "138",
          "MEDSTAF_CNT": "28",
          "HOSPTLRM_CNT": "30",
          "TREAT_SBJECT_CONT": "내과, 정형외과, 신경외과, 마취통증의학과, 영상의학과, 가정의학과",
          "TOT_AR": "3725.4",
          "REFINE_WGS84_LAT": "37.6990933161",
          "REFINE_WGS84_LOGT": "126.7559079500"
        }
]